//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PF.DB.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol
    {
        public string TipoUsuario { get; set; }
        public int Cedula { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
