//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PF.DB.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjeta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tarjeta()
        {
            this.Estado_Tarjeta = new HashSet<Estado_Tarjeta>();
        }
    
        public long NumeroTarjeta { get; set; }
        public string TipoTarjeta { get; set; }
        public int LimiteCredito { get; set; }
        public int MontoExtra { get; set; }
        public System.DateTime FechaActivacion { get; set; }
        public string Origen { get; set; }
        public int Cedula { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estado_Tarjeta> Estado_Tarjeta { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
